Week 7
alievgithub/MIPT_advanced_python_fall pull request #5
Opened 2020-11-04 18:14 UTC by alievgithub

2020-11-06 11:13 UTC, alekseik1 requested changes
1. Нет `requirements.txt` в корне проекта
2. Тесты не запускаются:
```python
(venv) (base) ➜  w7 git:(w7) ✗ python -m pytest -vv
============================================ test session starts =============================================
platform darwin -- Python 3.8.6, pytest-6.1.2, py-1.9.0, pluggy-0.13.1 -- /Users/a.kozharin/kids/aliev-artem/w7/venv/bin/python
cachedir: .pytest_cache
rootdir: /Users/a.kozharin/kids/aliev-artem/w7
collected 0 items / 2 errors

=================================================== ERRORS ===================================================
_______________________________ ERROR collecting tests/test_my_complex_math.py _______________________________
ImportError while importing test module '/Users/a.kozharin/kids/aliev-artem/w7/tests/test_my_complex_math.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
venv/lib/python3.8/site-packages/_pytest/python.py:571: in _importtestmodule
    mod = import_path(self.fspath, mode=importmode)
venv/lib/python3.8/site-packages/_pytest/pathlib.py:517: in import_path
    importlib.import_module(module_name)
/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
<frozen importlib._bootstrap>:1014: in _gcd_import
    ???
<frozen importlib._bootstrap>:991: in _find_and_load
    ???
<frozen importlib._bootstrap>:975: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:671: in _load_unlocked
    ???
venv/lib/python3.8/site-packages/_pytest/assertion/rewrite.py:171: in exec_module
    exec(co, module.__dict__)
tests/test_my_complex_math.py:1: in <module>
    from my_mathematics.simple_math import MyComplexMath
E   ModuleNotFoundError: No module named 'my_mathematics.simple_math'
___________________________________ ERROR collecting tests/test_my_math.py ___________________________________
ImportError while importing test module '/Users/a.kozharin/kids/aliev-artem/w7/tests/test_my_math.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
venv/lib/python3.8/site-packages/_pytest/python.py:571: in _importtestmodule
    mod = import_path(self.fspath, mode=importmode)
venv/lib/python3.8/site-packages/_pytest/pathlib.py:517: in import_path
    importlib.import_module(module_name)
/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
<frozen importlib._bootstrap>:1014: in _gcd_import
    ???
<frozen importlib._bootstrap>:991: in _find_and_load
    ???
<frozen importlib._bootstrap>:975: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:671: in _load_unlocked
    ???
venv/lib/python3.8/site-packages/_pytest/assertion/rewrite.py:171: in exec_module
    exec(co, module.__dict__)
tests/test_my_math.py:1: in <module>
    from my_mathematics.simple_math import MyMath
E   ModuleNotFoundError: No module named 'my_mathematics.simple_math'
========================================== short test summary info ===========================================
ERROR tests/test_my_complex_math.py
ERROR tests/test_my_math.py
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 2 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
============================================= 2 errors in 0.21s ==============================================
(venv) (base) ➜  w7 git:(w7) ✗
```

2020-11-08 12:58 UTC, alekseik1 commented
@alievgithub будешь тесты исправлять?

2020-11-08 20:44 UTC, alievgithub commented
> @alievgithub будешь тесты исправлять?

Буду, как убунту восстановлю, что-то он совсем не фурычит, в busybox ввыкидывает, сейчас делаю загрузучную флешку!

2020-11-10 10:32 UTC, alievgithub commented
По идее все готово, проверяйте.

2020-11-14 10:12 UTC, alekseik1 commented
В `MyMath` не тестируется `sqrt`. 13/15

2020-11-15 22:18 UTC, alievgithub commented
Исправил, теперь и корень тестит

2020-11-17 12:57 UTC, alekseik1 approved these changes
Ок, 15/15

2020-11-17 12:57 UTC, merged