Week 8
alievgithub/MIPT_advanced_python_fall pull request #6
Opened 2020-11-15 22:19 UTC by alievgithub

2020-11-22 15:40 UTC, alekseik1 requested changes
1. Хорошие тесты, особенно на `Maximize`.
2. В Фибоначчи реализовано немного не совсем то поведение, посмотри комменты.
3. Не нашел `print_map`.

2020-11-22 15:40 UTC, alekseik1 commented on w8/GenCodes/FiboGen.py
> +    return next(f)
Это не совсем генератор. Генератор -- это то, что внутри ты написал.

2020-11-23 17:06 UTC, alievgithub commented on w8/GenCodes/FiboGen.py
> +    return next(f)
тогда мне следует две отдельные функции написать, или достаточно просто переименовать названия?

2020-11-23 17:12 UTC, alievgithub commented on w8/GenCodes/FiboGen.py
> +    return next(f)
А на счет print_map() не совсем понял, может просто не заметили из-за странного названия кода, так как он есть в файле FuncWOfor.py

2020-11-24 17:56 UTC, alekseik1 requested changes

2020-11-24 17:56 UTC, alekseik1 commented on w8/GenCodes/FiboGen.py
> +def Fibo(n):
Не работает:
```python
(base) ➜  GenCodes git:(w8) ✗ cat FiboGen.py
def Fibo(n):
    def FiboGen():
        first = 0
        second = 1
        while True:
            yield first
            first, second = second, first + second

    f = Fibo()
    for i in range(n):
        next(f)
    return next(f)

for i in Fibo(6):
    print(i)
```
выдает
```python
(base) ➜  GenCodes git:(w8) ✗ python FiboGen.py
Traceback (most recent call last):
  File "FiboGen.py", line 14, in <module>
    for i in Fibo(6):
  File "FiboGen.py", line 9, in Fibo
    f = Fibo()
TypeError: Fibo() missing 1 required positional argument: 'n'
```
хотя ожидалось, что покажется первые 6 чисел Фибоначчи.

Кстати, числа надо считать на лету, а не заранее.

2020-11-25 08:57 UTC, alievgithub commented on w8/GenCodes/FiboGen.py
> +def Fibo(n):
теперь работает

2020-11-30 17:16 UTC, alekseik1 commented
34/36

2020-11-30 17:16 UTC, merged