Week 9 Ex 1 - Ex 4
alievgithub/MIPT_advanced_python_fall pull request #7
Opened 2020-11-18 12:06 UTC by alievgithub

2020-11-22 15:25 UTC, alekseik1 requested changes
1. `BinTree` не является итерируемым.

9/11

2020-11-22 15:25 UTC, alekseik1 commented on w9/DataProcessing.py
> +            dispersion = np.var(arr)
Можно считать дисперсию и среднее только по мере необходимости (т.е. при обработке сигналов). Не обязательно на каждое добавление элементов пересчитывать их.

2020-11-24 00:26 UTC, alievgithub commented
Сделал бинарное дерево итерируемым

2020-11-24 17:48 UTC, alekseik1 commented
Ок, 11/11

2020-11-24 17:49 UTC, merged